* Ruby Khipu

A Ruby investigation and implementation of the following paper:

https://ccsenet.org/journal/index.php/cis/article/view/0/52950

We'll start by implementing my understanding of khipu as an organized system of
integer data. The paper says a khipu is "heirarchical, partially
unsorted, grouped and summed". Its a tree structure(heirarchical) that allows
arbitrary insertion (partially unsorted). Elements of the tree can be grouped,
and groups have a built in summation via the "top-cord" feature.

** A Cord of Knots is an Integer

In the most basic interpretation, we read each knots as an integer. The the last
element is the units place, the next-to-last is the tens place and so on. Each cord
thus encodes a number in base 10, with each knot being a digit.

Naively, we could implement this as an array that only holds integers from 0-9. Without
types in Ruby, we just have to abide by the contract manually. Here is a sketch of
a Cord object which evaluates to an integer:

#+begin_src ruby :results code :exports both
  cord = Class.new do
    attr_reader :knots

    def initialize
      @knots = []
    end

    def <<(val) = @knots << val
    def to_s = @knots.join
    def to_i = to_s.to_i
  end

  a_cord = cord.new
  a_cord << 1
  a_cord << 2
  a_cord << 3

  {
    knots: a_cord.knots,
    value: a_cord.to_i,
  }
#+end_src

#+RESULTS:
#+begin_src ruby
{knots: [1, 2, 3], value: 123}
#+end_src

Adding a knot for 1 in the hundreds place, 2 in the tens, and 3 in the units
we get the integer 123. The idiomatic Ruby way to convert an array of integers
into a number is to use ~array.join.to_i~. It isn't going to be the most
efficient solution to convert cords to numbers, but its intuitive. We can do
an optimization exercise later.

** Strand base class

The paper's interface proposes a base class that is an iterable. I debate about
simply inheriting from ~Array~ to build up the Khipu from Groups of Cords. But the
standard way of making an iterable in Ruby is to include ~Enumerable~ and define
~each~. May as well use an array as the object member that holds ~knots~.

#+begin_src ruby :tangle yes
  class Strand
    include Enumerable

    attr_accessor :knots

    def initialize
      @knots = []
      @group = false
      @colour = nil
      @direction = false
    end

    def each(&block) = knots.each(&block)
    def <<(val) = knots << val
    def length = count
    def insert(i, x) = knots[i] = x
    def append(item) = knots.append(item)
    def concat(strand) = strand.each { |item| append(item) }
    def clear = knots.clear
    def copy = Marshal.load(Marshal.dump(self))

    # TODO
    def decrypt(key) = nil
    def encrypt = nil

    def to_s
      "#{group ? 1 : ''}|#{colour}|#{direction ? 1 : ''}|#{knots.join}"
    end

    private

    attr_reader   :group,
                  :colour,
                  :direction
  end
#+end_src

** Cord

#+begin_src ruby :tangle yes
  class Cord < Strand
    def colour=(rgba_array)
      @colour = Colour.new(*rgba_array)
    end

    def direction=(bool)
      @direction = bool
    end

    def +(cord)
      new_value = to_i + cord.to_i
      @knots = new_value.to_s.chars.map(&:to_i)
      self
    end

    def to_i = knots.join.to_i

    class Colour
      def initialize(r,g,b,a)
        @colour = [r,g,b,a]
      end

      def red = @colour[0]
      def green = @colour[1]
      def blue = @colour[2]
      def alpha = @colour[3]

      def to_s = "(#{red}, #{green}, #{blue}, #{alpha})"
    end
  end
#+end_src

** Group

#+begin_src ruby :tangle yes
  class Group < Strand
    attr_reader :top_cord

    def initialize(has_top = true)
      super()
      @group = true
      @has_top = has_top
      @top_cord = Cord.new if has_top?
    end

    def has_top? = !!@has_top

    def add_to_top_cord(cord)
      if has_top?
        @top_cord += cord
      else
        @top_cord = Cord.new
        @has_top = true
        @top_cord += cord
      end
    end

    def append(cord, top_cord = true)
      @knots << cord

      add_to_top_cord(cord) if top_cord
    end

    def to_s = ["1|||", @top_cord, knots].join("\n  ")

    def to_i
      return top_cord.to_i if has_top?

      knots.map(&:to_i).sum
    end

    def clear
      knots.clear
      @top_cord = Cord.new
      self
    end

    def concat(cords, update_top_cord = true)
      cords.each { |cord|
        add_to_top_cord(cord) if update_top_cord && has_top?
        knots << cord
      }
    end

    def insert(i, cord, top_cord = true)
      knots[i] = cord

      add_to_top_cord(cord) if top_cord
    end
  end
#+end_src

** Khipu

#+begin_src ruby :tangle yes
  class Khipu < Strand
    def to_s = knots.join("\n")

    # TODO
    def deserialize(path)
      File.readlines(path).each do |line|
        parts = line.split
        case parts
        in ["1", *]
          knots << Group.new
        in ["", String, *, String]
        end
      end
    end

    def new_cord = Cord.new
    def new_group = Group.new
    def serialize(path, indent=4, spaces=0) = nil
  end
#+end_src

* Notes
** Reference
*** Python Interface from the paper
#+begin_src python
  # 2.2.1 Class base
  # The interface of base (Base in Python) is given as follows.
  class Base:
  def __init__(self) ...
  def __iter__(self) ...
  def __len__(self) ...
  def __next__(self) ...
  def append(self, x) ...
  def clear(self) ...
  def copy(self) ...
  def decrypt(self, key) ...
  def encrypt(self, key) ...
  def extend(self, iterable) ...
  def insert(self, i, x) ...

  # 2.2.2 Class cord
  # The interface of cord (Cord) is given as follows.
  class Cord(Base):
  def __init__(self, colour_=None, direction_=False) ...
  def __add__(self, cord) ...
  @property
  def colour(self) ...
  @colour.setter
  def colour(self, colour_) ...
  def copy(self) ...
  @property
  def direction(self) ...
  @direction.setter
  def direction(self, direction_) ...
  def val(self) ...

  # 2.2.3 Class group
  # The interface of group (Group) is given as follows.
  class Group(Base):
  def __init__(self, top_cord_=True) ...
  def add_to_top_cord(self, cord) ...
  def append(self, cord, top_cord_=True) ...
  def clear(self) ...
  def copy(self) ...
  # http://cis.ccsenet.org Computer and Information Science Vol. 19, No. 1; 2026 56
  def extend(self, cords, top_cord_=True) ...
  def insert(self, i, cord, top_cord_=True) ...
  @property
  def top_cord(self) ...
  @top_cord.setter
  def top_cord(self, top_cord_) ...

  # 2.2.4 Class quipu
  # The interface of quipu (Quipu) is given as follows.
  class Quipu(Base):
  def __init__(self) ...
  def copy(self) ...
  def deserialize(self, path) ...
  def new_cord(self) ...
  def new_group(self) ...
  def serialize(self, path, indent=4, spaces=0
#+end_src
** Optimizing Cord to Integer

#+begin_src ruby :results output :exports both
  @knots = [1,2,3,4,5,6,7,8,9,0]

  def coercion
    @knots.join.to_i
  end

  def functional
    @knots.reduce(0) { |memo, i| memo * 10 + i }
  end

  def imperative_each
    result = 0
    @knots.each do |i|
      result = result * 10 + i
    end
    result
  end

  def imperative_while
    result = 0
    i = 0
    len = @knots.length
    while i < len
      result = result * 10 + @knots[i]
      i += 1
    end
    result
  end

  require 'benchmark'

  n = 1_000_000

  Benchmark.bm do |x|
    x.report("coercion:") { n.times { coercion } }
    x.report("functional") { n.times { functional } }
    x.report("imperative_each:") { n.times { imperative_each } }
    x.report("imperative_while:") { n.times { imperative_while } }
  end
#+end_src

#+RESULTS:
:                        user     system      total        real
: coercion:          0.766777   0.003551   0.770328 (  0.770378)
: functional         0.350813   0.001270   0.352083 (  0.352157)
: imperative_each:   0.266080   0.000249   0.266329 (  0.266360)
: imperative_while:  0.257264   0.000087   0.257351 (  0.257376)

** COMMENT Create a Knot Abstraction?

Knots are like bytes, in that they could represent different kinds of information.
For the initial example, we assume that a khipu is composed of groups of cords where
each knot is of the same type. In our case, it is Integers, but a Knot could be
anything really. Perhaps the color of the Cord tells you how to interpret the knots
in a cord. Practically, keeping the elements of a Cord as Integers, but allowing
arbitrarily high numbers would work like a primary key pointer to some other
data structure. This would screw up the methods for adding things together.

