#+TITLE: Ruby Khipu
#+AUTHOR: Grant Shangreaux

* Introduction

A Ruby investigation and implementation of the data structure proposed based
on the Inka [[https://www.khipufieldguide.com/guidebook/Introduction.html][Khipu]]
that is proposed in the following paper:

[[https://ccsenet.org/journal/index.php/cis/article/view/0/52950][Quipu Data Structure]] by Richard Dosselmann, Edward Doolittle, Vatika Tayal

** What is a Khipu?

The Inkan civilization and people of the central Andes recorded information
by tying knots into cords of woven threads. Most of what has been deciphered
is numeric information. The knots are tied on cords in a way to represent a
base 10 system. One type of knot per digit 1-9, the absence of a knot being
zero, plus position on a cord encodes any integer. In addition, the khipu
knots had variations making them easier to read, or encoding additional
information as signs.

#+begin_quote
Since the ones position on quipu cords are shown in a distinctive way (i.e., using
long knots and figure-eight knots), it is usually clear where a number ends. Thus,
it is possible that a single quipu cord could contain several numbers.[fn:1]
#+end_quote

More information is present than has been deciphered. Cords come in different
colors and weaving styles. Cords are clustered into groups, and some have a
single cord tied off the top in a different direction.

** A Cord of Knots is an Integer

In the most basic interpretation, we read the combined knots of a cord as an
integer.

For example, say we use dashes (~---~) for the cord, then symbols to
represent knots, which in turn represent a numeral:

1 → ●

4 → ⁛

5 → ⸭

Then this cord: ~--●--⸭-----⁛--~ is the integer 1,504.

What matters in this interpretation are the POSITION of the knot and the VALUE
of the knot as a number. Because POSITION is relevant, we know that the numeral
4 (⁛) is in the units place, there's an implied zero in the tens, 5 (⸭) in the
hundreds place, and 1 (●) in the thousands.

~--1--5--0--4--~
~--●--⸭-----⁛--~

Each cord encodes an integer, with each knot being a base 10 digit.[fn:3]

** Strands of Information

The Khipu is an information dense object meant for human interpretation.
Khipu specialists called "khipu-kamayuq", maker-of-knots, encoded structured
and narrative meaning into the woven cords. There was a spiritual connection
cloth as a sacred object, and more meaning was added by the knot-makers. We
will focus on interpreting them as numbers, but the khipu-kamayuq certainly
had more ways of reading the knots. Even with only numbers, khipu were powerful
ways of storing and communicating information.

#+begin_quote
I think of khipu as an ancient form of “spreadsheet”, made from woven cord. That’s
an intentional metaphor - a spreadsheet both calculates (expected) and communicates
(unexpected). Most modern khipu scholars agree that khipus serve both purposes, but
beyond that, much disagreement exists. Our ability to “read” a khipu has been lost,
and khipus remain one of the few remaining ancient communication mediums that remain
enigmatic...[fn:2]
#+end_quote

Computer data structures are similar, but built for binary machine
interpretation first. An integer is stored in memory as a series of zeroes and
ones. 11000000111001 in binary is 12345 in base 10. It is more efficient for
humans to use 10 as a base to encode integers, but a computer simply can't.
Every bit of data is made up of only ones and zeroes. The amazing part is how
almost anything we can think of is encoded in binary. If a stranger from
the future found a string of ones-and-zeroes, would the ability to read the
encoded information be lost as well?

** Weaving and Tangling

Transforming the cloth Khipu, cords woven and knotted by hand, into a computer
data structure feels like an interesting space between present, past, and future.
So much of my mind is occupied by computer languages and data modeling. As
an indigenous American, the opportunity to weave indigenous knowledge and
ways of communication into my world is a welcome thing.

This document is written as a [[https://en.wikipedia.org/wiki/Literate_programming#bodyContent][literate program.]] The code blocks encountered
here are the source for the Ruby code files present in the repository. It is
a happy coincidence that my favorite way to write is with [[https://orgmode.org/][Org mode for GNU Emacs]].
It allows us to *tangle* out the source code woven into the document. The tree
structure of an org-mode document is heirarchical and grouped like Khipu.
Working with programs this way helps see and understand information in new ways.

* Implementation

We'll start by implementing my understanding of khipu as an organized system of
integer data. The paper says a khipu is "heirarchical, partially
unsorted, grouped and summed". Its a tree structure(heirarchical) that allows
arbitrary insertion (partially unsorted). Elements of the tree can be grouped,
and groups have a built in summation via the "top-cord" feature.

** A Simple Ruby Cord

If you aren't a programmer, don't worry. I hope that the physical example
of the khipu will stay in your mind as we explore how Ruby encodes information
in text. The code examples will avoid complexity and illustrate some fundamental
parts of thinking with a computer language. If you're curious to know more,
[[./ruby.org]] holds my thoughts on understanding it better.

Naively, a ~cord~ could be an ~Array~ that only holds integers from 0-9.
Here is a sketch of a Cord object which evaluates to an integer:

#+begin_src ruby :results code :exports both
  cord = Class.new do
    attr_reader :knots

    def initialize
      @knots = []
    end

    def <<(val) = @knots << val
    def to_s = @knots.join
    def to_i = to_s.to_i
  end

  a_cord = cord.new
  a_cord << 1 << 2 << 3

  {
    knots: a_cord.knots,
    value: a_cord.to_i,
  }
#+end_src

#+RESULTS:
#+begin_src ruby
{knots: [1, 2, 3], value: 123}
#+end_src

Adding a knot for 1 in the hundreds place, 2 in the tens, and 3 in the units
we get the integer 123. The idiomatic Ruby way to convert an array of integers
into a number is to use ~array.join.to_i~. It isn't going to be the most
efficient solution to convert cords to numbers, but its intuitive. We can do
an optimization exercise later.

** Strand base class

The paper's interface proposes a base class that is an iterable.

#+begin_src ruby :tangle yes
  class Strand
    attr_accessor :knots

    def initialize
      @knots = []
      @group = false
      @colour = nil
      @direction = false
    end

    def each(&block) = knots.each(&block)
    def <<(val) = knots << val
    def length = count
    def insert(i, x) = knots[i] = x
    def append(item) = knots.append(item)
    def concat(strand) = strand.each { |item| append(item) }
    def clear = knots.clear
    def copy = Marshal.load(Marshal.dump(self))

    # TODO
    def decrypt(key) = nil
    def encrypt = nil

    def to_s
      "#{group ? 1 : ''}|#{colour}|#{direction ? 1 : ''}|#{knots.join}"
    end

    private

    attr_reader   :group,
                  :colour,
                  :direction
  end
#+end_src

** Cord

#+begin_src ruby :tangle yes
  class Cord < Strand
    def colour=(rgba_array)
      @colour = Colour.new(*rgba_array)
    end

    def direction=(bool)
      @direction = bool
    end

    def +(cord)
      new_value = to_i + cord.to_i
      @knots = new_value.to_s.chars.map(&:to_i)
      self
    end

    def to_i = knots.join.to_i

    class Colour
      def initialize(r,g,b,a)
        @colour = [r,g,b,a]
      end

      def red = @colour[0]
      def green = @colour[1]
      def blue = @colour[2]
      def alpha = @colour[3]

      def to_s = "(#{red}, #{green}, #{blue}, #{alpha})"
    end
  end
#+end_src

** Group

#+begin_src ruby :tangle yes
  class Group < Strand
    attr_reader :top_cord

    def initialize(has_top = true)
      super()
      @group = true
      @has_top = has_top
      @top_cord = Cord.new if has_top?
    end

    def has_top? = !!@has_top

    def add_to_top_cord(cord)
      if has_top?
        @top_cord += cord
      else
        @top_cord = Cord.new
        @has_top = true
        @top_cord += cord
      end
    end

    def append(cord, top_cord = true)
      @knots << cord

      add_to_top_cord(cord) if top_cord
    end

    def to_s = ["1|||", @top_cord, knots].join("\n  ")

    def to_i
      return top_cord.to_i if has_top?

      knots.map(&:to_i).sum
    end

    def clear
      knots.clear
      @top_cord = Cord.new
      self
    end

    def concat(cords, update_top_cord = true)
      cords.each { |cord|
        add_to_top_cord(cord) if update_top_cord && has_top?
        knots << cord
      }
    end

    def insert(i, cord, top_cord = true)
      knots[i] = cord

      add_to_top_cord(cord) if top_cord
    end
  end
#+end_src

** Khipu

#+begin_src ruby :tangle yes
  class Khipu < Strand
    def to_s = knots.join("\n")

    # TODO
    def deserialize(path)
      File.readlines(path).each do |line|
        parts = line.split
        case parts
        in ["1", *]
          knots << Group.new
        in ["", String, *, String]
        end
      end
    end

    def new_cord = Cord.new
    def new_group = Group.new
    def serialize(path, indent=4, spaces=0) = nil
  end
#+end_src

* Notes
** Optimizing Cord to Integer

#+begin_src ruby :results output :exports both
  @knots = [1,2,3,4,5,6,7,8,9,0]

  def coercion
    @knots.join.to_i
  end

  def functional
    @knots.reduce(0) { |memo, i| memo * 10 + i }
  end

  def imperative_each
    result = 0
    @knots.each do |i|
      result = result * 10 + i
    end
    result
  end

  def imperative_while
    result = 0
    i = 0
    len = @knots.length
    while i < len
      result = result * 10 + @knots[i]
      i += 1
    end
    result
  end

  require 'benchmark'

  n = 1_000_000

  Benchmark.bm do |x|
    x.report("coercion:") { n.times { coercion } }
    x.report("functional") { n.times { functional } }
    x.report("imperative_each:") { n.times { imperative_each } }
    x.report("imperative_while:") { n.times { imperative_while } }
  end
#+end_src

#+RESULTS:
:                        user     system      total        real
: coercion:          0.766777   0.003551   0.770328 (  0.770378)
: functional         0.350813   0.001270   0.352083 (  0.352157)
: imperative_each:   0.266080   0.000249   0.266329 (  0.266360)
: imperative_while:  0.257264   0.000087   0.257351 (  0.257376)

** Reference
*** Python Interface from the paper
#+begin_src python
  # 2.2.1 Class base
  # The interface of base (Base in Python) is given as follows.
  class Base:
  def __init__(self) ...
  def __iter__(self) ...
  def __len__(self) ...
  def __next__(self) ...
  def append(self, x) ...
  def clear(self) ...
  def copy(self) ...
  def decrypt(self, key) ...
  def encrypt(self, key) ...
  def extend(self, iterable) ...
  def insert(self, i, x) ...

  # 2.2.2 Class cord
  # The interface of cord (Cord) is given as follows.
  class Cord(Base):
  def __init__(self, colour_=None, direction_=False) ...
  def __add__(self, cord) ...
  @property
  def colour(self) ...
  @colour.setter
  def colour(self, colour_) ...
  def copy(self) ...
  @property
  def direction(self) ...
  @direction.setter
  def direction(self, direction_) ...
  def val(self) ...

  # 2.2.3 Class group
  # The interface of group (Group) is given as follows.
  class Group(Base):
  def __init__(self, top_cord_=True) ...
  def add_to_top_cord(self, cord) ...
  def append(self, cord, top_cord_=True) ...
  def clear(self) ...
  def copy(self) ...
  # http://cis.ccsenet.org Computer and Information Science Vol. 19, No. 1; 2026 56
  def extend(self, cords, top_cord_=True) ...
  def insert(self, i, cord, top_cord_=True) ...
  @property
  def top_cord(self) ...
  @top_cord.setter
  def top_cord(self, top_cord_) ...

  # 2.2.4 Class quipu
  # The interface of quipu (Quipu) is given as follows.
  class Quipu(Base):
  def __init__(self) ...
  def copy(self) ...
  def deserialize(self, path) ...
  def new_cord(self) ...
  def new_group(self) ...
  def serialize(self, path, indent=4, spaces=0
#+end_src
** COMMENT Create a Knot Abstraction?

Knots are like bytes, in that they could represent different kinds of information.
For the initial example, we assume that a khipu is composed of groups of cords where
each knot is of the same type. In our case, it is Integers, but a Knot could be
anything really. Perhaps the color of the Cord tells you how to interpret the knots
in a cord. Practically, keeping the elements of a Cord as Integers, but allowing
arbitrarily high numbers would work like a primary key pointer to some other
data structure. This would screw up the methods for adding things together.

* Footnotes

[fn:1] https://en.wikipedia.org/wiki/Quipu
[fn:2] https://www.khipufieldguide.com/guidebook/Introduction.html
[fn:3] https://en.wikipedia.org/wiki/Decimal

