* Understanding a bit of Ruby

This is a spin-off for those of you who may want to understand programming
languages more. I began writing this in the Khipu document but it quickly
became a diversion into a programming tutorial. I leave it here incomplete,
but available for those who are curious.

** Ruby Arrays are Sequences

The [[https://www.ruby-lang.org/en/][Ruby Programming Language]] has a sequence [[https://en.wikipedia.org/wiki/Data_structure][data structure]] called an ~Array~.
An ~Array~ is a collection of elements stored in computer memory. The elements can be
retrieved by their *index*. Most programming languages start counting from
zero, so the first element in an ~Array~ would be at index ~0~. Ruby uses a special
syntax to input and output arrays, using square brackets ~[]~. The square brackets
there are an empty array!

If we let an ~Array~ stand in for our Cord, and regular numerals stand in for Knots,
then writing the number 1,504 above would be written like this in Ruby:

#+name: simple-array-cord
#+begin_src ruby
  [1, 5, 0, 4]
#+end_src

** A Cord is a Sequence of Elements

"Sequence of Elements" is a loaded term. We're heading towards computer world.
For our purposes, an *ELEMENT* is one part of a *SEQUENCE*. The elements of a
sequence follow an order, so they model the position part of the Khipu I mentioned
above. If a Cord is a Sequence of Elements, the elements are the Knots, and the
Cord itself is the Sequence.

Now, computers use many flavors of sequences all the time. The primary thing they
have in common is that they have zero or more elements, and you often want to do
some operation that applies to some or all of the elements within the sequence.

** /Aside : Playing with literate code/

If you are reading this from the comfort of Emacs, you would be in an ~org-mode~
buffer. Any block of source code can be evaluated on your computer, provided you've
configured it. Assuming perhaps you haven't, but you /are/ in Emacs, move the cursor
to the source block below and press Control-C twice on your keyboard. Emacs will ask
If you want to run the code. Type ~yes~ to do so. It will enable you to run Ruby code
from within this file.

#+name: load-ruby-for-org-babel
#+begin_src emacs-lisp :results none
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (ruby . t)))
#+end_src

Now assuming that worked you should be able to do the same on the following block
of Ruby code. If you're just here to read, notice how printing the ~cord~ variable
is different than printing each knot of the cord individually:

#+begin_src ruby :results output :exports both
  cord = [1, 5, 0, 4]
  print(cord, "\n")
  cord.each { |knot| print(knot) }
#+end_src

#+RESULTS:
: [1, 5, 0, 4]
: 1504

I'm leaving the result of myself running it here in the document, if you run it
again it won't change. Try changing one of the knot numbers to see what happens
when you evaluate the code again.

** Reading Ruby

Lets take a look at that code again and go through it line by line:

#+begin_src ruby :results output :exports both
  cord = [1, 5, 0, 4]
  print(cord, "\n")
  cord.each { |knot| print(knot) }
#+end_src

*** Assigning a variable

#+begin_src ruby
  cord = [1, 5, 0, 4]
#+end_src

"Ruby, the value of the *symbol* ~cord~ equals the ~Array [1, 5, 0, 4]~."
The elements of the array ~cord~ are all integers. Index ~0~ points to the value
~1~ up to index ~3~ pointing at the value ~4~.

To take a number /out/ of the sequence, Ruby has *the index operator ~[]~*. Hmmm.
That is the same symbol as making an ~Array~. Think of it as a window that lets you
zoom to any point of the sequence to see what is there. It also lets you put
something else in that spot. Like this:

#+begin_src example
  cord[0]
  => 1
  cord[3] = 9
  => 9
  cord
  => [1, 5, 0, 9]
#+end_src

*** Printing some text

#+begin_src ruby :results none
  print(cord, "\n")
#+end_src

The second line prints the array and a newline character (~"\n"~). Well, it doesn't
print it on paper on a real-life printer. The text prints to the "standard
output" which you can imagine like a terminal screen. You can print to other places
too, like a file or stream. The important part for us is printing lets us see what
the *value* of the variable ~cord~ is... when it is represented as text to print.
Here it prints the array the same way that we type it in ~[1, 5, 0, 4]~. This is
handy because you can cut and paste it into your Ruby interpreter if needed.

*** Print each knot in the cord, one at a time

#+begin_src ruby :results none
  cord.each { |knot| print(knot) }
#+end_src

The third line takes advantage of the ~Array~'s nature as a sequence. In Ruby, the
word for any type of sequence is ~Enumerable~. An array is enumerated by integers
starting at ~0~, up to the length of the list -1. The main message that ~Enumerable~
objects respond to is ~each~. ~Array#each~ starts going through the list,
*yielding* each element to the *block* that follows.

Now this is really cool. The *block* is the /code/ surrounded by curly braces:
~{ |knot| print(knot) }~. The insides of this block can be any Ruby code at all.
This is powerful, now with /anything/ that acts like an ~Enumerable~ and responds
to ~each~ can pass its elements, one at a time, to code that can be customized
for what ever purpose is needed at the time.

The ~|knot|~ part assigns one element at a time to become THE ~knot~ for a moment,
then it gets printed. Then the ~cord.each~ yields the next knot to the block
until the end of the sequence.
